# Generated by Django 5.0.2 on 2024-04-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
