# Generated by Django 5.0.2 on 2024-05-05 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('MENTION', 'Mention'), ('FOLLOW', 'Follow'), ('MESSAGE', 'Message'), ('BOOKMARK', 'Bookmark')], max_length=128)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by', to=settings.AUTH_USER_MODEL)),
                ('user_to_notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notif_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notificationtype')),
            ],
        ),
    ]
