# Generated by Django 5.0.2 on 2024-02-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_post_image_remove_post_video_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media',
            new_name='file',
        ),
    ]
