# Generated by Django 5.0.2 on 2024-03-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isReply',
        ),
    ]
