# Generated by Django 5.0.2 on 2024-03-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_remove_post_isreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isReply',
            field=models.BooleanField(default=False),
        ),
    ]
